defaults:
  - _default_optimization_attack
  - _self_
type: HF_GradInv
label_strategy: ye_res34 #yin #wainakh-simple

objective:
  type: dyna-layer-rand-cosine-similarity
  scale: 1
  start: 100
  min_start: 25
  broken_tail: 0
  peroid_Add10: 500
  min_weight_scale: 1
  max_weight_scale: 1

restarts:
  num_trials: 1
  scoring: cosine-similarity

init: randn
optim:
  optimizer: adam
  signed: "hard_quantify"
  mul_scale: 2
  step_size: 0.1
  boxed: True
  max_iterations: 15_000
  step_size_decay: step-lr
  langevin_noise: 0
  warmup: 0
  pixel_decay: 0.0
  distance_constrain:
    stop_iter: 200
    decay_rate: 1
    decay_dis_rate: 1
  #  grad_clip: None

  callback: 1000

regularization:
  total_variation:
    scale: 5e-3
    inner_exp: 1
    outer_exp: 1
    tv_start: 3000
  norm:
    scale: 1e-8
    pnorm: 2
    norm_start: 30000
  deep_inversion:
    scale: 1e-4
    first_bn_multiplier: 1.3
    second_bn_multiplier: 3
    deep_inv_start: 5000
    deep_inv_stop: 30000
  group_regular:
    scale: 0.05
    totalseeds: 1
    startIter: 50000
    updateRegPeriod: 200
    mode: "lazy"
    weighted: False

save_dir: "./custom_data/test_recon/"
sat_ratio: 1.0

augmentations:
  #  focus:
  #    size: 224
  #    std: 0
  #  discrete_shift:
  #    lim: 8
#  gaussianblur:
#    radius: 101
#    std: 1

gaussianblur:
  radius: 21
  tiny_std: 0.2 # 0.7 for 4
  large_std: 0.2
  post_std: 1.0

gaussianblur_start: 50000  # 3000